### ISSUE TITLE
Test the DC3DCD

### ISSUE THREAD

**Issue by IHe-KaiI** [IdeGelis/torch-points3d-DC3DCD#1]
Hi, thanks for your amazing work. I'm trying to test the Urb3DCD data. As I have set the repo, how can I run the change detection inference? Will you release your checkpoint for Change Detection tasks? Thanks!

**Comment by IdeGelis** [comment]
Hello, 

Thank you for your interest to DC3DCD.
To launch the training, use the script train_DC3DCD.py and the inference test_DC3DCD.py. 
Before you need to set the configuration files available in the folder conf.
On the link below, you can download the trained models with and without handcrafted features as input. As you probably read in the publication, to have correct results, you should add the handcrafted features. 

[https://filesender.renater.fr/?s=download&token=250ecbd3-df53-46cf-91ad-853e2a9e0925](https://filesender.renater.fr/?s=download&token=250ecbd3-df53-46cf-91ad-853e2a9e0925)

I also added codes for handcrafted feature extraction in the folder : HandCrafedFeaturesExtraction

Best regards,

Iris
